[build-system]
requires = [
    "setuptools>=59",
    "wheel",
    "cmake",
    "ninja"
]

build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
skip = ["*-win32", "*-manylinux_i686", "*-musllinux_i686", "pp*"]