name: Build wheels

on: [workflow_dispatch]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
    
      # Used to host cibuildwheel
      - uses: actions/setup-python@v5

      - name: setup devcmd
        if: ${{ matrix.os == 'windows-latest' }}
            # NOTE: this is necessary to correctly find and use cl.exe
        uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: Bootstrap vcpkg
        run: |
          git submodule update --init --recursive
          python bootstrap_vcpkg.py

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.19.1

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          MACOSX_DEPLOYMENT_TARGET: '10.13' # 10.13 is the minimum version that partially supports c++17

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl