name: Build wheels

on: [workflow_dispatch]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        # os: [ubuntu-latest, macos-13, macos-14]
        # os: [windows-latest]

    steps:
      - uses: actions/checkout@v4
    
      # Used to host cibuildwheel
      - uses: actions/setup-python@v5

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.19.1 pipx pytest apsw numpy

      - uses: ilammy/msvc-dev-cmd@v1 

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Bootstrap vcpkg
        run: |
          git submodule update --init --recursive
          python bootstrap_vcpkg.py

      - name: Build wheels
        run: pipx run cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl